/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'startTime' : Time,
  'endTime' : Time,
  'description' : string,
}
export type DateTime = bigint;
export type DietPreference = { 'nonVegetarian' : null } |
  { 'vegetarian' : null };
export interface FocusBlock {
  'id' : string,
  'startTime' : Time,
  'status' : FocusBlockStatus,
  'endTime' : Time,
  'description' : string,
}
export type FocusBlockStatus = { 'modified' : null } |
  { 'suggested' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Goal = { 'betterFocus' : null } |
  { 'betterSleep' : null } |
  { 'lessStress' : null };
export interface Meeting {
  'startTime' : DateTime,
  'isRepeating' : boolean,
  'endTime' : DateTime,
  'repeatInterval' : [] | [number],
  'description' : string,
  'diaryEntries' : Array<Activity>,
  'priority' : number,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserPreferences {
  'typicalMeetingLoad' : bigint,
  'sleepTime' : Time,
  'dietPreference' : DietPreference,
  'wakeTime' : Time,
  'caffeineHabits' : string,
  'goals' : Array<Goal>,
  'workHours' : [Time, Time],
}
export interface UserProfile {
  'userId' : UserId,
  'lastCalendarSync' : [] | [Time],
  'preferences' : UserPreferences,
  'weeklyInsights' : Array<string>,
  'contentPreferences' : { 'avoidCertainContent' : boolean, 'useAI' : boolean },
}
export interface _SERVICE {
  'addActivity' : ActorMethod<[UserId, Activity], undefined>,
  'addFocusBlock' : ActorMethod<[UserId, FocusBlock], undefined>,
  'addMeeting' : ActorMethod<[UserId, Meeting], undefined>,
  'addStressCheckIn' : ActorMethod<[UserId, bigint], undefined>,
  'createOrUpdateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'getActivities' : ActorMethod<[UserId], Array<Activity>>,
  'getFocusBlocks' : ActorMethod<[UserId], Array<FocusBlock>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'markComplete' : ActorMethod<[string, string], undefined>,
  'removeMeeting' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];