/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'endTime' : Time,
  'description' : IDL.Text,
});
export const FocusBlockStatus = IDL.Variant({
  'modified' : IDL.Null,
  'suggested' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FocusBlock = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : FocusBlockStatus,
  'endTime' : Time,
  'description' : IDL.Text,
});
export const DateTime = IDL.Int;
export const Meeting = IDL.Record({
  'startTime' : DateTime,
  'isRepeating' : IDL.Bool,
  'endTime' : DateTime,
  'repeatInterval' : IDL.Opt(IDL.Nat8),
  'description' : IDL.Text,
  'diaryEntries' : IDL.Vec(Activity),
  'priority' : IDL.Nat8,
});
export const DietPreference = IDL.Variant({
  'nonVegetarian' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const Goal = IDL.Variant({
  'betterFocus' : IDL.Null,
  'betterSleep' : IDL.Null,
  'lessStress' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'typicalMeetingLoad' : IDL.Int,
  'sleepTime' : Time,
  'dietPreference' : DietPreference,
  'wakeTime' : Time,
  'caffeineHabits' : IDL.Text,
  'goals' : IDL.Vec(Goal),
  'workHours' : IDL.Tuple(Time, Time),
});
export const UserProfile = IDL.Record({
  'userId' : UserId,
  'lastCalendarSync' : IDL.Opt(Time),
  'preferences' : UserPreferences,
  'weeklyInsights' : IDL.Vec(IDL.Text),
  'contentPreferences' : IDL.Record({
    'avoidCertainContent' : IDL.Bool,
    'useAI' : IDL.Bool,
  }),
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func([UserId, Activity], [], []),
  'addFocusBlock' : IDL.Func([UserId, FocusBlock], [], []),
  'addMeeting' : IDL.Func([UserId, Meeting], [], []),
  'addStressCheckIn' : IDL.Func([UserId, IDL.Nat], [], []),
  'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
  'getActivities' : IDL.Func([UserId], [IDL.Vec(Activity)], ['query']),
  'getFocusBlocks' : IDL.Func([UserId], [IDL.Vec(FocusBlock)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'markComplete' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeMeeting' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const FocusBlockStatus = IDL.Variant({
    'modified' : IDL.Null,
    'suggested' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FocusBlock = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : FocusBlockStatus,
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const DateTime = IDL.Int;
  const Meeting = IDL.Record({
    'startTime' : DateTime,
    'isRepeating' : IDL.Bool,
    'endTime' : DateTime,
    'repeatInterval' : IDL.Opt(IDL.Nat8),
    'description' : IDL.Text,
    'diaryEntries' : IDL.Vec(Activity),
    'priority' : IDL.Nat8,
  });
  const DietPreference = IDL.Variant({
    'nonVegetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'betterFocus' : IDL.Null,
    'betterSleep' : IDL.Null,
    'lessStress' : IDL.Null,
  });
  const UserPreferences = IDL.Record({
    'typicalMeetingLoad' : IDL.Int,
    'sleepTime' : Time,
    'dietPreference' : DietPreference,
    'wakeTime' : Time,
    'caffeineHabits' : IDL.Text,
    'goals' : IDL.Vec(Goal),
    'workHours' : IDL.Tuple(Time, Time),
  });
  const UserProfile = IDL.Record({
    'userId' : UserId,
    'lastCalendarSync' : IDL.Opt(Time),
    'preferences' : UserPreferences,
    'weeklyInsights' : IDL.Vec(IDL.Text),
    'contentPreferences' : IDL.Record({
      'avoidCertainContent' : IDL.Bool,
      'useAI' : IDL.Bool,
    }),
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func([UserId, Activity], [], []),
    'addFocusBlock' : IDL.Func([UserId, FocusBlock], [], []),
    'addMeeting' : IDL.Func([UserId, Meeting], [], []),
    'addStressCheckIn' : IDL.Func([UserId, IDL.Nat], [], []),
    'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
    'getActivities' : IDL.Func([UserId], [IDL.Vec(Activity)], ['query']),
    'getFocusBlocks' : IDL.Func([UserId], [IDL.Vec(FocusBlock)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'markComplete' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeMeeting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };