/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface UserPreferences {
    typicalMeetingLoad: bigint;
    sleepTime: Time;
    dietPreference: DietPreference;
    wakeTime: Time;
    caffeineHabits: string;
    goals: Array<Goal>;
    workHours: [Time, Time];
}
export type Time = bigint;
export interface Meeting {
    startTime: DateTime;
    isRepeating: boolean;
    endTime: DateTime;
    repeatInterval?: number;
    description: string;
    diaryEntries: Array<Activity>;
    priority: number;
}
export interface FocusBlock {
    id: string;
    startTime: Time;
    status: FocusBlockStatus;
    endTime: Time;
    description: string;
}
export type DateTime = bigint;
export interface Activity {
    id: string;
    startTime: Time;
    endTime: Time;
    description: string;
}
export interface UserProfile {
    userId: UserId;
    lastCalendarSync?: Time;
    preferences: UserPreferences;
    weeklyInsights: Array<string>;
    contentPreferences: {
        avoidCertainContent: boolean;
        useAI: boolean;
    };
}
export enum DietPreference {
    nonVegetarian = "nonVegetarian",
    vegetarian = "vegetarian"
}
export enum FocusBlockStatus {
    modified = "modified",
    suggested = "suggested",
    rejected = "rejected",
    accepted = "accepted"
}
export enum Goal {
    betterFocus = "betterFocus",
    betterSleep = "betterSleep",
    lessStress = "lessStress"
}
export interface backendInterface {
    addActivity(userId: UserId, activity: Activity): Promise<void>;
    addFocusBlock(userId: UserId, focusBlock: FocusBlock): Promise<void>;
    addMeeting(userId: UserId, meeting: Meeting): Promise<void>;
    addStressCheckIn(userId: UserId, level: bigint): Promise<void>;
    createOrUpdateUserProfile(userProfile: UserProfile): Promise<void>;
    getActivities(userId: UserId): Promise<Array<Activity>>;
    getFocusBlocks(userId: UserId): Promise<Array<FocusBlock>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    markComplete(userId: string, meetingId: string): Promise<void>;
    removeMeeting(userId: string, meetingId: string): Promise<void>;
}
import type { Activity as _Activity, DateTime as _DateTime, DietPreference as _DietPreference, FocusBlock as _FocusBlock, FocusBlockStatus as _FocusBlockStatus, Goal as _Goal, Meeting as _Meeting, Time as _Time, UserId as _UserId, UserPreferences as _UserPreferences, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: UserId, arg1: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1);
            return result;
        }
    }
    async addFocusBlock(arg0: UserId, arg1: FocusBlock): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFocusBlock(arg0, to_candid_FocusBlock_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFocusBlock(arg0, to_candid_FocusBlock_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMeeting(arg0: UserId, arg1: Meeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeeting(arg0, to_candid_Meeting_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeeting(arg0, to_candid_Meeting_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addStressCheckIn(arg0: UserId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStressCheckIn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStressCheckIn(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(to_candid_UserProfile_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(to_candid_UserProfile_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActivities(arg0: UserId): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities(arg0);
            return result;
        }
    }
    async getFocusBlocks(arg0: UserId): Promise<Array<FocusBlock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFocusBlocks(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFocusBlocks(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async markComplete(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markComplete(arg0, arg1);
            return result;
        }
    }
    async removeMeeting(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMeeting(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMeeting(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DietPreference_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietPreference): DietPreference {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_FocusBlockStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FocusBlockStatus): FocusBlockStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FocusBlock_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FocusBlock): FocusBlock {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    status: _FocusBlockStatus;
    endTime: _Time;
    description: string;
}): {
    id: string;
    startTime: Time;
    status: FocusBlockStatus;
    endTime: Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_FocusBlockStatus_n19(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime,
        description: value.description
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    lastCalendarSync: [] | [_Time];
    preferences: _UserPreferences;
    weeklyInsights: Array<string>;
    contentPreferences: {
        avoidCertainContent: boolean;
        useAI: boolean;
    };
}): {
    userId: UserId;
    lastCalendarSync?: Time;
    preferences: UserPreferences;
    weeklyInsights: Array<string>;
    contentPreferences: {
        avoidCertainContent: boolean;
        useAI: boolean;
    };
} {
    return {
        userId: value.userId,
        lastCalendarSync: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastCalendarSync)),
        preferences: from_candid_UserPreferences_n25(_uploadFile, _downloadFile, value.preferences),
        weeklyInsights: value.weeklyInsights,
        contentPreferences: value.contentPreferences
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    typicalMeetingLoad: bigint;
    sleepTime: _Time;
    dietPreference: _DietPreference;
    wakeTime: _Time;
    caffeineHabits: string;
    goals: Array<_Goal>;
    workHours: [_Time, _Time];
}): {
    typicalMeetingLoad: bigint;
    sleepTime: Time;
    dietPreference: DietPreference;
    wakeTime: Time;
    caffeineHabits: string;
    goals: Array<Goal>;
    workHours: [Time, Time];
} {
    return {
        typicalMeetingLoad: value.typicalMeetingLoad,
        sleepTime: value.sleepTime,
        dietPreference: from_candid_DietPreference_n27(_uploadFile, _downloadFile, value.dietPreference),
        wakeTime: value.wakeTime,
        caffeineHabits: value.caffeineHabits,
        goals: from_candid_vec_n29(_uploadFile, _downloadFile, value.goals),
        workHours: value.workHours
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    modified: null;
} | {
    suggested: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): FocusBlockStatus {
    return "modified" in value ? FocusBlockStatus.modified : "suggested" in value ? FocusBlockStatus.suggested : "rejected" in value ? FocusBlockStatus.rejected : "accepted" in value ? FocusBlockStatus.accepted : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nonVegetarian: null;
} | {
    vegetarian: null;
}): DietPreference {
    return "nonVegetarian" in value ? DietPreference.nonVegetarian : "vegetarian" in value ? DietPreference.vegetarian : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    betterFocus: null;
} | {
    betterSleep: null;
} | {
    lessStress: null;
}): Goal {
    return "betterFocus" in value ? Goal.betterFocus : "betterSleep" in value ? Goal.betterSleep : "lessStress" in value ? Goal.lessStress : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FocusBlock>): Array<FocusBlock> {
    return value.map((x)=>from_candid_FocusBlock_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n30(_uploadFile, _downloadFile, x));
}
function to_candid_DietPreference_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietPreference): _DietPreference {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_FocusBlockStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FocusBlockStatus): _FocusBlockStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FocusBlock_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FocusBlock): _FocusBlock {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Meeting_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Meeting): _Meeting {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    typicalMeetingLoad: bigint;
    sleepTime: Time;
    dietPreference: DietPreference;
    wakeTime: Time;
    caffeineHabits: string;
    goals: Array<Goal>;
    workHours: [Time, Time];
}): {
    typicalMeetingLoad: bigint;
    sleepTime: _Time;
    dietPreference: _DietPreference;
    wakeTime: _Time;
    caffeineHabits: string;
    goals: Array<_Goal>;
    workHours: [_Time, _Time];
} {
    return {
        typicalMeetingLoad: value.typicalMeetingLoad,
        sleepTime: value.sleepTime,
        dietPreference: to_candid_DietPreference_n11(_uploadFile, _downloadFile, value.dietPreference),
        wakeTime: value.wakeTime,
        caffeineHabits: value.caffeineHabits,
        goals: to_candid_vec_n13(_uploadFile, _downloadFile, value.goals),
        workHours: value.workHours
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: Time;
    status: FocusBlockStatus;
    endTime: Time;
    description: string;
}): {
    id: string;
    startTime: _Time;
    status: _FocusBlockStatus;
    endTime: _Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: to_candid_FocusBlockStatus_n3(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime,
        description: value.description
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: DateTime;
    isRepeating: boolean;
    endTime: DateTime;
    repeatInterval?: number;
    description: string;
    diaryEntries: Array<Activity>;
    priority: number;
}): {
    startTime: _DateTime;
    isRepeating: boolean;
    endTime: _DateTime;
    repeatInterval: [] | [number];
    description: string;
    diaryEntries: Array<_Activity>;
    priority: number;
} {
    return {
        startTime: value.startTime,
        isRepeating: value.isRepeating,
        endTime: value.endTime,
        repeatInterval: value.repeatInterval ? candid_some(value.repeatInterval) : candid_none(),
        description: value.description,
        diaryEntries: value.diaryEntries,
        priority: value.priority
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: UserId;
    lastCalendarSync?: Time;
    preferences: UserPreferences;
    weeklyInsights: Array<string>;
    contentPreferences: {
        avoidCertainContent: boolean;
        useAI: boolean;
    };
}): {
    userId: _UserId;
    lastCalendarSync: [] | [_Time];
    preferences: _UserPreferences;
    weeklyInsights: Array<string>;
    contentPreferences: {
        avoidCertainContent: boolean;
        useAI: boolean;
    };
} {
    return {
        userId: value.userId,
        lastCalendarSync: value.lastCalendarSync ? candid_some(value.lastCalendarSync) : candid_none(),
        preferences: to_candid_UserPreferences_n9(_uploadFile, _downloadFile, value.preferences),
        weeklyInsights: value.weeklyInsights,
        contentPreferences: value.contentPreferences
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietPreference): {
    nonVegetarian: null;
} | {
    vegetarian: null;
} {
    return value == DietPreference.nonVegetarian ? {
        nonVegetarian: null
    } : value == DietPreference.vegetarian ? {
        vegetarian: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    betterFocus: null;
} | {
    betterSleep: null;
} | {
    lessStress: null;
} {
    return value == Goal.betterFocus ? {
        betterFocus: null
    } : value == Goal.betterSleep ? {
        betterSleep: null
    } : value == Goal.lessStress ? {
        lessStress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FocusBlockStatus): {
    modified: null;
} | {
    suggested: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == FocusBlockStatus.modified ? {
        modified: null
    } : value == FocusBlockStatus.suggested ? {
        suggested: null
    } : value == FocusBlockStatus.rejected ? {
        rejected: null
    } : value == FocusBlockStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Goal>): Array<_Goal> {
    return value.map((x)=>to_candid_Goal_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
